### ISSUE TITLE
无法捐赠

### ISSUE THREAD

**Issue by Chloeunterwegs** [xisuo67/Unbelievable-Box#4]
作者您好，想体验下小红书数据采集的功能，这个box的付款二维码直接不显示，捐赠不了。是否能修复，或者提供其他捐赠方式。

**Comment by xisuo67** [comment]
有什么问题，可以通过程序右上角邮箱图标联系我，这个软件在重构中，暂时有很多问题需要修复

**Comment by xisuo67** [comment]
> 作者您好，想体验下小红书数据采集的功能，这个box的付款二维码直接不显示，捐赠不了。是否能修复，或者提供其他捐赠方式。

由于兼容性问题暂时开放授权网站:http://xisuo67.system.yfloves.cn/
